services:
  saleor-dashboard:
    container_name: saleor-dashboard
    env_file:
      - ../saleor-platform/backend.env
    build:
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL}
        APP_MOUNT_URI: ${APP_MOUNT_URI:-/dashboard/}
        EXTENSIONS_API_URL: ${EXTENSIONS_API_URL:-}
        STATIC_URL: ${STATIC_URL:-/dashboard/}
        SKIP_SOURCEMAPS: ${SKIP_SOURCEMAPS:-true}
        LOCALE_CODE: ${LOCALE_CODE:-EN}
        BUILD_NODE_OPTIONS: ${DASHBOARD_BUILD_NODE_OPTIONS:---max-old-space-size=4096}
    environment:
      API_URL: ${API_URL}
      APP_MOUNT_URI: ${APP_MOUNT_URI:-/dashboard/}
      EXTENSIONS_API_URL: ${EXTENSIONS_API_URL:-}
      IS_CLOUD_INSTANCE: ${IS_CLOUD_INSTANCE:-false}
      LOCALE_CODE: ${LOCALE_CODE:-EN}
    restart: always
    cpus: ${DASHBOARD_CPUS:-0.25}
    mem_limit: ${DASHBOARD_MEMORY_LIMIT:-128m}
    memswap_limit: ${DASHBOARD_MEMORY_SWAP_LIMIT:-128m}
    pids_limit: 100
    ports:
      - ${DASHBOARD_PORT:-9000}:80
    networks:
      - saleor_dashboard_network

networks:
  saleor_dashboard_network:
    external: false
